import { promises as fs } from "node:fs";
import { tmpdir } from "node:os";
import * as path from "node:path";

import type { FastifyInstance } from "fastify";
import { afterEach, describe, expect, it } from "vitest";
import { z } from "zod";

import { ProjectRepositoryError } from "../../src/app/projects/project-repository.js";
import { buildApp } from "../../src/api/app.js";
import {
  apiErrorResponseSchema,
  createApiSuccessResponse
} from "../../src/schema/api.js";

function parseApiError(response: {
  headers: { readonly [key: string]: unknown };
  json(): unknown;
}) {
  expect(response.headers["content-type"]).toMatch(/^application\/json/);
  const parsed = apiErrorResponseSchema.safeParse(response.json());
  expect(parsed.success).toBe(true);
  if (!parsed.success) {
    throw parsed.error;
  }

  expect(parsed.data.error.requestId).not.toBe("");
  return parsed.data.error;
}

describe("common API error handling", () => {
  let app: FastifyInstance | undefined;

  afterEach(async () => {
    if (app !== undefined) {
      await app.close();
      app = undefined;
    }
  });

  it("returns a contract-shaped 404 for an unknown API route", async () => {
    app = buildApp();

    const response = await app.inject({
      method: "GET",
      url: "/api/unknown"
    });

    expect(response.statusCode).toBe(404);
    const error = parseApiError(response);
    expect(error.code).toBe("API_NOT_FOUND");
    expect(error.details).toEqual([]);
  });

  it("converts nested Zod paths and array indexes into details", async () => {
    app = buildApp();
    const inputSchema = z
      .object({
        sections: z.array(
          z
            .object({
              lines: z.array(
                z
                  .object({
                    title: z.string().min(1)
                  })
                  .strict()
              )
            })
            .strict()
        )
      })
      .strict();

    app.post("/api/zod-validation", async (request) => {
      const input = inputSchema.parse(request.body);
      return createApiSuccessResponse(input);
    });

    const response = await app.inject({
      method: "POST",
      url: "/api/zod-validation",
      payload: {
        sections: [
          {
            lines: [
              {
                title: ""
              }
            ]
          }
        ]
      }
    });

    expect(response.statusCode).toBe(422);
    const error = parseApiError(response);
    expect(error.code).toBe("REQUEST_VALIDATION_FAILED");
    expect(error.details).toHaveLength(1);
    expect(error.details[0]?.path).toEqual([
      "sections",
      0,
      "lines",
      0,
      "title"
    ]);
    expect(error.details[0]?.message).toContain("string");
  });

  it("converts Fastify request validation into a 400 response", async () => {
    app = buildApp();
    app.post(
      "/api/fastify-validation",
      {
        schema: {
          body: {
            type: "object",
            required: ["sections"],
            properties: {
              sections: {
                type: "array",
                items: {
                  type: "object",
                  required: ["title"],
                  properties: {
                    title: { type: "string" }
                  }
                }
              }
            }
          }
        }
      },
      async () => createApiSuccessResponse({ ok: true })
    );

    const response = await app.inject({
      method: "POST",
      url: "/api/fastify-validation",
      payload: {
        sections: [{}]
      }
    });

    expect(response.statusCode).toBe(400);
    const error = parseApiError(response);
    expect(error.code).toBe("REQUEST_VALIDATION_FAILED");
    expect(error.details[0]?.path).toEqual(["body", "sections", 0, "title"]);
  });

  it("converts malformed JSON generated by Fastify into the same 400 contract", async () => {
    app = buildApp();
    app.post("/api/invalid-json", async () =>
      createApiSuccessResponse({ ok: true })
    );

    const response = await app.inject({
      method: "POST",
      url: "/api/invalid-json",
      headers: {
        "content-type": "application/json"
      },
      payload: "{invalid-json"
    });

    expect(response.statusCode).toBe(400);
    const error = parseApiError(response);
    expect(error.code).toBe("REQUEST_VALIDATION_FAILED");
    expect(error.details).toEqual([]);
  });

  it("preserves repository business codes, statuses, and issues", async () => {
    app = buildApp();
    app.get("/api/project-not-found", async () => {
      throw new ProjectRepositoryError(
        "PROJECT_NOT_FOUND",
        404,
        "internal path C:\\workspace\\project.json"
      );
    });
    app.get("/api/project-revision-conflict", async () => {
      throw new ProjectRepositoryError(
        "PROJECT_REVISION_CONFLICT",
        409,
        "internal conflict detail"
      );
    });
    app.get("/api/project-validation", async () => {
      throw new ProjectRepositoryError(
        "PROJECT_CANDIDATE_VALIDATION_FAILED",
        422,
        "internal validation detail",
        [
          {
            path: ["sections", 1, "lines", 2, "subtitleText"],
            message: "字幕テキストが必要です。"
          }
        ]
      );
    });

    const notFoundResponse = await app.inject({
      method: "GET",
      url: "/api/project-not-found"
    });
    expect(notFoundResponse.statusCode).toBe(404);
    const notFoundError = parseApiError(notFoundResponse);
    expect(notFoundError.code).toBe("PROJECT_NOT_FOUND");
    expect(JSON.stringify(notFoundResponse.json())).not.toContain(
      "internal path"
    );

    const conflictResponse = await app.inject({
      method: "GET",
      url: "/api/project-revision-conflict"
    });
    expect(conflictResponse.statusCode).toBe(409);
    expect(parseApiError(conflictResponse).code).toBe(
      "PROJECT_REVISION_CONFLICT"
    );

    const validationResponse = await app.inject({
      method: "GET",
      url: "/api/project-validation"
    });
    expect(validationResponse.statusCode).toBe(422);
    const validationError = parseApiError(validationResponse);
    expect(validationError.code).toBe("PROJECT_CANDIDATE_VALIDATION_FAILED");
    expect(validationError.details).toEqual([
      {
        path: ["sections", 1, "lines", 2, "subtitleText"],
        message: "字幕テキストが必要です。"
      }
    ]);
  });

  it("returns a generic 500 without exposing unexpected error data", async () => {
    app = buildApp();
    const secret = "UNSAFE_SENTINEL_MARKDOWN_API_KEY";
    app.post("/api/unexpected", async (request) => {
      const requestData = JSON.stringify({
        body: request.body,
        headers: request.headers
      });
      throw new Error(`${secret} ${requestData}`, {
        cause: {
          secret,
          absolutePath: "C:\\private\\source.md"
        }
      });
    });

    const response = await app.inject({
      method: "POST",
      url: "/api/unexpected",
      headers: {
        authorization: "Bearer UNSAFE_AUTHORIZATION_SENTINEL",
        cookie: "session=UNSAFE_COOKIE_SENTINEL"
      },
      payload: {
        markdown: "UNSAFE_INPUT_MATERIAL_SENTINEL"
      }
    });

    expect(response.statusCode).toBe(500);
    const error = parseApiError(response);
    expect(error.code).toBe("INTERNAL_SERVER_ERROR");
    expect(error.message).toBe("サーバーで予期しないエラーが発生しました。");
    expect(error.details).toEqual([]);
    expect(JSON.stringify(response.json())).not.toContain(secret);
    expect(JSON.stringify(response.json())).not.toContain(
      "UNSAFE_AUTHORIZATION_SENTINEL"
    );
    expect(JSON.stringify(response.json())).not.toContain(
      "UNSAFE_COOKIE_SENTINEL"
    );
    expect(JSON.stringify(response.json())).not.toContain(
      "UNSAFE_INPUT_MATERIAL_SENTINEL"
    );
    expect(JSON.stringify(response.json())).not.toContain("C:\\private");
  });
});

describe("API 404 behavior with static fallback", () => {
  let app: FastifyInstance | undefined;
  let staticRoot: string | undefined;

  afterEach(async () => {
    if (app !== undefined) {
      await app.close();
      app = undefined;
    }
    if (staticRoot !== undefined) {
      await fs.rm(staticRoot, { recursive: true, force: true });
      staticRoot = undefined;
    }
  });

  it("keeps SPA fallback for non-API GETs and JSON 404 for API paths", async () => {
    staticRoot = await fs.mkdtemp(path.join(tmpdir(), "subdub-api-static-"));
    await fs.writeFile(
      path.join(staticRoot, "index.html"),
      "<!doctype html><div id=\"root\">SPA</div>",
      "utf8"
    );
    app = buildApp({ staticRoot });

    const spaResponse = await app.inject({
      method: "GET",
      url: "/projects/example"
    });
    expect(spaResponse.statusCode).toBe(200);
    expect(spaResponse.headers["content-type"]).toMatch(/^text\/html/);
    expect(spaResponse.body).toContain("SPA");

    const apiResponse = await app.inject({
      method: "GET",
      url: "/api/missing"
    });
    expect(apiResponse.statusCode).toBe(404);
    const error = parseApiError(apiResponse);
    expect(error.code).toBe("API_NOT_FOUND");
    expect(apiResponse.body).not.toContain("<div id=\"root\">");
  });

  it("uses the same API error contract without static files", async () => {
    const responses: Array<{ statusCode: number; body: string }> = [];
    staticRoot = await fs.mkdtemp(path.join(tmpdir(), "subdub-api-compare-"));

    for (const useStaticFallback of [false, true]) {
      app = useStaticFallback ? buildApp({ staticRoot }) : buildApp();
      const response = await app.inject({
        method: "GET",
        url: "/api/missing"
      });
      responses.push({
        statusCode: response.statusCode,
        body: response.body
      });
      await app.close();
      app = undefined;
    }

    expect(responses[0]?.statusCode).toBe(404);
    expect(responses[1]?.statusCode).toBe(404);
    expect(
      apiErrorResponseSchema.parse(JSON.parse(responses[0]?.body ?? "{}"))
        .error.code
    ).toBe("API_NOT_FOUND");
    expect(
      apiErrorResponseSchema.parse(JSON.parse(responses[1]?.body ?? "{}"))
        .error.code
    ).toBe("API_NOT_FOUND");
  });
});
